// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Data;

namespace WebApplication2.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApplication2.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Product1 Description",
                            Discount = 20,
                            ImagePath = "images\\product-1-1.jpg",
                            Name = "Product1",
                            Price = 10
                        },
                        new
                        {
                            Id = 2,
                            Description = "Product2 Description",
                            Discount = 35,
                            ImagePath = "images\\product-2-1.jpg",
                            Name = "Product2",
                            Price = 20
                        },
                        new
                        {
                            Id = 3,
                            Description = "Product3 Description",
                            Discount = 0,
                            ImagePath = "images\\product-3-1.jpg",
                            Name = "Product3",
                            Price = 30
                        },
                        new
                        {
                            Id = 4,
                            Description = "Product4 Description",
                            Discount = 5,
                            ImagePath = "images\\product-4-1.jpg",
                            Name = "Product4",
                            Price = 40
                        },
                        new
                        {
                            Id = 5,
                            Description = "Product5 Description",
                            Discount = 15,
                            ImagePath = "images\\product-5-1.jpg",
                            Name = "Product5",
                            Price = 50
                        },
                        new
                        {
                            Id = 6,
                            Description = "Product6 Description",
                            Discount = 10,
                            ImagePath = "images\\product-6-1.jpg",
                            Name = "Product6",
                            Price = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
